from simple_calculator_class import MoreFeaturesCalculator
def calculator_menu():
    print("")
    print("╔═══════════════════ \033[0;32mRAD CALCULATOR\033[0m ════════════════════╗")
    print("║\033[4mAvailable operations:\033[0m                                  ║")
    print("║  [1] +  -> Addition                                   ║")
    print("║  [2] -  -> Subtraction                                ║")
    print("║  [3] *  -> Multiplication                             ║")
    print("║  [4] /  -> Division                                   ║")
    print("║  [5] ** -> Exponent (Power)                           ║")
    print("║  [6] %  -> Modulo (Remainder)                         ║")
    print("║  [7] %  -> Percentage                                 ║")
    print("║  [8] avg -> Average (multiple numbers)                ║")
    print("║                                                       ║")
    print("║\033[3m Did you know?: The word 'Rad' in tagalog is MAANGAS!!\033[0m ║")
    print("╚═══════════════════════════════════════════════════════╝")
